name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  MacOS:
    name: Build on MacOS
    permissions: write-all
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8

      - name: Install
        run: pnpm install

      - name: Build
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          APPLE_SIGNING_IDENTITY: "Developer ID Application: DUZHONG CHEN (N4MJHBTFAR)"
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin
          pnpm tauri build --target universal-apple-darwin
      
      - name: Upload
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
          FIREBASE_ADMINSDK: ${{ secrets.FIREBASE_ADMINSDK }}
        run: |
          echo $FIREBASE_ADMINSDK > ./scripts/t1-api-firebase-adminsdk.json
          pnpm run upload
